<div class="stockTradingHome">
<h1 class="main-page__h1">Обучение торговле акциями на фондовых биржах США</h1>
<div class="main-page__wrapper">
<div class="main-video main-video_new"><!--<iframe width="560" height="315" src="https://www.youtube.com/embed/cLXCyPaSUzE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>--> <iframe width="560" height="315" src="https://www.youtube.com/embed/piG4CdW6p9A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe></div>
</div>
<h4 style="text-align: left;">Торговля акциями – это просто!</h4>
<p style="text-align: left;"><img style="float: left; margin-right: 5px; margin-left: 5px;" src="images/check.png" alt="" width="40" height="40" /> Если вы решили всерьез заняться трейдингом на фондовом рынке, то обратившись в нашу компанию вы получите максимум поддержки и сопровождения. Зная потребности и проблемы трейдеров, мы способны предоставить эффективное обучение трейдингу и всю необходимую инфраструктуру.</p>
<h4 style="text-align: left;">Обучение трейдингу от компании SDG Trade</h4>
<p style="text-align: left;"><img style="float: left; margin-right: 5px; margin-left: 5px;" src="images/check.png" alt="" width="40" height="40" />Уже свыше 10 лет мы активно занимаемся подготовкой и обучением трейдеров. Мы предоставляем трейдеру знания, которые взяты из личного опыта профессиональных трейдеров, с которыми мы сотрудничаем и подтверждены положительными результатами учеников. Все курсы компании построены только на практике трейдеров и содержат рабочие стратегии.</p>
<h4 style="text-align: left;">Возможности для успешной торговли на NYSE, NASDAQ, AMEX</h4>
<p style="text-align: left;"><img style="float: left; margin-right: 5px; margin-left: 5px;" src="images/check.png" alt="" width="40" height="40" />Если вы уже готовы открыть торговый счет для работы на фондовом рынке США - обратитесь к нам. Мы предоставим вам полную консультацию по открытию счета у американских брокеров. В том числе компания SDG Trade предоставляет персональные консультации с профессиональными трейдерами и инвесторами.</p>
</div>